#!/bin/bash

name=$(./jq.exe -r '.name' data.json)
type=$(./jq.exe -r '.types[0].type.name' data.json)
weight=$(./jq.exe -r '.weight' data.json)
height=$(./jq.exe -r '.height' data.json)

# Convert units
formatted_weight=$(awk "BEGIN {printf \"%.1f\", $weight / 10}")
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height / 10}")

# Capitalize type
type=$(echo "$type" | sed 's/.*/\u&/')

# Final output (exact format checker wants)
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
